spring.datasource.url=jdbc:postgresql://dpg-d7uqffdckfvc73bgmg3g-a.oregon-postgres.render.com:5432/impactovisible_db
spring.datasource.username=impactovisible_db_user
spring.datasource.password=4RmeyFvvDr9Jzs5rpn3rtMtj4SrAdAlc
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=ImpactoVisibleSecretKey2025SuperSeguraParaJWT123456789
jwt.expiration=86400000
